import "./globals.css";
import Navbar from "./components/navbar";

export const metadata = {
  title: "EpiStats",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin ></link>
        <link href="https://fonts.googleapis.com/css2?family=Assistant:wght@200..800&family=Bebas+Neue&display=swap" rel="stylesheet"></link>
      </head>
      <body >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
